#############################################################################
# Makefile for building: libaudioconvert.so
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  audioconvert.pro
# Template: lib
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 -o Makefile audioconvert.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DNDEBUG
CFLAGS        = -m64 -pipe -O3 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -m64 -msse -msse2 -msse3 -mssse3 -msse4 -msse4.1 -msse4.2 -mavx -mf16c -fpic -fdata-sections -ffunction-sections -I/home/danek/Repos/audioconvert/thirdparty/include/linux -I/home/danek/Repos/audioconvert/platform/linux -I/home/danek/Repos/audioconvert/../auxiliary -I/home/danek/Repos/audioconvert/../boost -O3 -std=c++1y -Wall -W -Wno-parentheses -Wno-unused-variable -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-unused-but-set-variable -Wno-sign-compare -Wno-unused-function -Wno-switch -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = audioconvert1.0.0
DISTDIR = /home/danek/Repos/.int/audioconvert_release/audioconvert1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O3 -shared -Wl,-soname,libaudioconvert.so.1
LIBS          = $(SUBLIBS) -L/home/danek/Repos/audioconvert/../.dist -Wl,--version-script=/home/danek/Repos/audioconvert/platform/linux/audioconvert.lds -Wl,--unresolved-symbols=report-all -Wl,--gc-sections -Wl,-rpath,./ -lauxiliary -lflac -llame -lmpg123 -lvorbis -logg -O3 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ../.int/audioconvert_release/

####### Files

SOURCES       = source/AudioCodecs/AudioFile.cpp \
		source/AudioCodecs/FlacDecoder.cpp \
		source/AudioCodecs/FlacEncoder.cpp \
		source/AudioCodecs/MpegDecoder.cpp \
		source/AudioCodecs/MpegEncoder.cpp \
		source/AudioCodecs/OpusDecoder.cpp \
		source/AudioCodecs/OpusEncoder.cpp \
		source/AudioCodecs/VorbisDecoder.cpp \
		source/AudioCodecs/VorbisEncoder.cpp \
		source/AudioCodecs/WaveDecoder.cpp \
		source/AudioCodecs/WaveEncoder.cpp \
		source/AudioConverter/AudioConverter.cpp \
		source/AudioConverter/AudioConverterAPI.cpp 
OBJECTS       = ../.int/audioconvert_release/AudioFile.o \
		../.int/audioconvert_release/FlacDecoder.o \
		../.int/audioconvert_release/FlacEncoder.o \
		../.int/audioconvert_release/MpegDecoder.o \
		../.int/audioconvert_release/MpegEncoder.o \
		../.int/audioconvert_release/OpusDecoder.o \
		../.int/audioconvert_release/OpusEncoder.o \
		../.int/audioconvert_release/VorbisDecoder.o \
		../.int/audioconvert_release/VorbisEncoder.o \
		../.int/audioconvert_release/WaveDecoder.o \
		../.int/audioconvert_release/WaveEncoder.o \
		../.int/audioconvert_release/AudioConverter.o \
		../.int/audioconvert_release/AudioConverterAPI.o
DIST          = platform/linux/audioconvert.lds \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		audioconvert.pro source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioMetadata.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/FlacDecoder.h \
		source/AudioCodecs/FlacEncoder.h \
		source/AudioCodecs/MpegDecoder.h \
		source/AudioCodecs/MpegEncoder.h \
		source/AudioCodecs/OpusDecoder.h \
		source/AudioCodecs/OpusEncoder.h \
		source/AudioCodecs/VorbisDecoder.h \
		source/AudioCodecs/VorbisEncoder.h \
		source/AudioCodecs/WaveDecoder.h \
		source/AudioCodecs/WaveEncoder.h \
		source/AudioConverter/AudioConverter.h \
		source/AudioConverter/AudioConverterAPI.h source/AudioCodecs/AudioFile.cpp \
		source/AudioCodecs/FlacDecoder.cpp \
		source/AudioCodecs/FlacEncoder.cpp \
		source/AudioCodecs/MpegDecoder.cpp \
		source/AudioCodecs/MpegEncoder.cpp \
		source/AudioCodecs/OpusDecoder.cpp \
		source/AudioCodecs/OpusEncoder.cpp \
		source/AudioCodecs/VorbisDecoder.cpp \
		source/AudioCodecs/VorbisEncoder.cpp \
		source/AudioCodecs/WaveDecoder.cpp \
		source/AudioCodecs/WaveEncoder.cpp \
		source/AudioConverter/AudioConverter.cpp \
		source/AudioConverter/AudioConverterAPI.cpp
QMAKE_TARGET  = audioconvert
DESTDIR       = ../.dist/#avoid trailing-slash linebreak
TARGET        = libaudioconvert.so
TARGETA       = ../.dist/libaudioconvert.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c -include ../.int/audioconvert_release/audioconvert $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

../.dist/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d ../.dist/ || mkdir -p ../.dist/
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(DEL_FILE) ../.dist/$(TARGET)
	-$(MOVE) $(TARGET)  ../.dist/ 



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: audioconvert.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		audioconvert.pro
	$(QMAKE) -spec linux-g++-64 -o Makefile audioconvert.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
audioconvert.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile audioconvert.pro

qmake_all: FORCE


all: Makefile ../.dist/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) ../.int/audioconvert_release/audioconvert.gch/c ../.int/audioconvert_release/audioconvert.gch/c++
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../.dist/$(TARGET) 
	-$(DEL_FILE) $(TARGETA)
	-$(DEL_FILE) Makefile


####### Sub-libraries

###### Precompiled headers
../.int/audioconvert_release/audioconvert.gch/c: platform/linux/platform.h 
	@test -d ../.int/audioconvert_release/audioconvert.gch/ || mkdir -p ../.int/audioconvert_release/audioconvert.gch/
	$(CC) $(CFLAGS) $(INCPATH) -x c-header -c platform/linux/platform.h -o ../.int/audioconvert_release/audioconvert.gch/c

../.int/audioconvert_release/audioconvert.gch/c++: platform/linux/platform.h 
	@test -d ../.int/audioconvert_release/audioconvert.gch/ || mkdir -p ../.int/audioconvert_release/audioconvert.gch/
	$(CXX) $(CXXFLAGS) $(INCPATH) -x c++-header -c platform/linux/platform.h -o ../.int/audioconvert_release/audioconvert.gch/c++

check: first

compiler_no_pch_compiler_make_all:
compiler_no_pch_compiler_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

../.int/audioconvert_release/AudioFile.o: source/AudioCodecs/AudioFile.cpp source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/AudioFile.o source/AudioCodecs/AudioFile.cpp

../.int/audioconvert_release/FlacDecoder.o: source/AudioCodecs/FlacDecoder.cpp source/AudioCodecs/FlacDecoder.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/FlacDecoder.o source/AudioCodecs/FlacDecoder.cpp

../.int/audioconvert_release/FlacEncoder.o: source/AudioCodecs/FlacEncoder.cpp source/AudioCodecs/FlacEncoder.h \
		source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/FlacEncoder.o source/AudioCodecs/FlacEncoder.cpp

../.int/audioconvert_release/MpegDecoder.o: source/AudioCodecs/MpegDecoder.cpp source/AudioCodecs/MpegDecoder.h \
		source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/MpegDecoder.o source/AudioCodecs/MpegDecoder.cpp

../.int/audioconvert_release/MpegEncoder.o: source/AudioCodecs/MpegEncoder.cpp source/AudioCodecs/MpegEncoder.h \
		source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/MpegEncoder.o source/AudioCodecs/MpegEncoder.cpp

../.int/audioconvert_release/OpusDecoder.o: source/AudioCodecs/OpusDecoder.cpp source/AudioCodecs/OpusDecoder.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/OpusDecoder.o source/AudioCodecs/OpusDecoder.cpp

../.int/audioconvert_release/OpusEncoder.o: source/AudioCodecs/OpusEncoder.cpp source/AudioCodecs/OpusEncoder.h \
		source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/OpusEncoder.o source/AudioCodecs/OpusEncoder.cpp

../.int/audioconvert_release/VorbisDecoder.o: source/AudioCodecs/VorbisDecoder.cpp source/AudioCodecs/VorbisDecoder.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/VorbisDecoder.o source/AudioCodecs/VorbisDecoder.cpp

../.int/audioconvert_release/VorbisEncoder.o: source/AudioCodecs/VorbisEncoder.cpp source/AudioCodecs/VorbisEncoder.h \
		source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/VorbisEncoder.o source/AudioCodecs/VorbisEncoder.cpp

../.int/audioconvert_release/WaveDecoder.o: source/AudioCodecs/WaveDecoder.cpp source/AudioCodecs/WaveDecoder.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/WaveDecoder.o source/AudioCodecs/WaveDecoder.cpp

../.int/audioconvert_release/WaveEncoder.o: source/AudioCodecs/WaveEncoder.cpp source/AudioCodecs/WaveEncoder.h \
		source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		source/AudioCodecs/WaveDecoder.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/WaveEncoder.o source/AudioCodecs/WaveEncoder.cpp

../.int/audioconvert_release/AudioConverter.o: source/AudioConverter/AudioConverter.cpp source/AudioConverter/AudioConverter.h \
		source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		source/AudioConverter/AudioConverterAPI.h \
		source/AudioCodecs/WaveDecoder.h \
		source/AudioCodecs/WaveEncoder.h \
		source/AudioCodecs/FlacDecoder.h \
		source/AudioCodecs/FlacEncoder.h \
		source/AudioCodecs/MpegDecoder.h \
		source/AudioCodecs/MpegEncoder.h \
		source/AudioCodecs/OpusDecoder.h \
		source/AudioCodecs/OpusEncoder.h \
		source/AudioCodecs/VorbisDecoder.h \
		source/AudioCodecs/VorbisEncoder.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/AudioConverter.o source/AudioConverter/AudioConverter.cpp

../.int/audioconvert_release/AudioConverterAPI.o: source/AudioConverter/AudioConverterAPI.cpp source/AudioConverter/AudioConverterAPI.h \
		source/AudioConverter/AudioConverter.h \
		source/AudioCodecs/AudioFile.h \
		source/AudioCodecs/AudioSink.h \
		source/AudioCodecs/AudioMetadata.h \
		../.int/audioconvert_release/audioconvert.gch/c++
	$(CXX) -c -include ../.int/audioconvert_release/audioconvert $(CXXFLAGS) $(INCPATH) -o ../.int/audioconvert_release/AudioConverterAPI.o source/AudioConverter/AudioConverterAPI.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

